apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: es-ingress-external
  annotations: 
     nginx.ingress.kubenets.io/proxy-bodu-size : 50m
     nginx.ingress.kubenets.io/rewrite-target: /$1
  labels:
    name: es-ingress-external
spec:
  ingressClassName : ingress-external
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/api/helloworld/(.*)"
        backend:
          service:
            name: helloworld
            port: 
              number: 8080
